#version 430
layout(local_size_x = 64) in;

layout(binding=0) uniform atomic_uint dead_particles_stack_counter;

layout(std430, binding=0) buffer dead_particles_stack {
    uint dead_particles[];
};

layout(std430, binding=1) buffer particle_positions {
    vec4 positions[];
};

layout(std430, binding=2) buffer particle_velocities {
    vec4 velocities[];
};

layout(std430, binding=3) buffer particle_lifetimes {
    float lifetimes[];
};

layout(std430, binding=4) buffer particle_renderpass_ids {
    uint renderpass_ids[];
};

uniform uint current_renderpass;

// -=-=-=-=-

layout(location = 1) uniform vec4 offset;
layout(location = 2) uniform vec4 player_position;
layout(location = 3) uniform vec4 player_velocity;

uint inv_id = uint(gl_GlobalInvocationID.x);
void main() {
    if(inv_id == 1 && atomicCounter(dead_particles_stack_counter) > 0){
        uint particle_idx = dead_particles[atomicCounterDecrement(dead_particles_stack_counter)];
        renderpass_ids[particle_idx] = current_renderpass;
        lifetimes[particle_idx] = 1;
        velocities[particle_idx] = player_velocity*0.5;
        positions[particle_idx].xyz = player_position.xyz + offset.xyz + player_velocity.xyz/4;
    }
}