#version 430
layout(local_size_x = 64) in;

layout(binding=0) uniform atomic_uint dead_particles_stack_counter;

layout(std430, binding=0) buffer dead_particles_stack {
    uint dead_particles[];
};

layout(std430, binding=1) buffer particle_positions {
    vec4 positions[];
};

layout(std430, binding=2) buffer particle_velocities {
    vec4 velocities[];
};

layout(std430, binding=3) buffer particle_lifetimes {
    float lifetimes[];
};

layout(std430, binding=4) buffer particle_renderpass_ids {
    uint renderpass_ids[];
};

uniform uint current_renderpass;

// -=-=-=-=-

uniform vec4 offset;
uniform vec4 projectile_position;
uniform uint particle_count;

float rand(vec2 co){
    return fract(sin(dot(co, vec2(12.9898, 78.233))) * 43758.5453);
}

uint inv_id = uint(gl_GlobalInvocationID.x);
void main() {
    if(inv_id < particle_count && atomicCounter(dead_particles_stack_counter) > 0){
        uint particle_idx = dead_particles[atomicCounterDecrement(dead_particles_stack_counter)];
        renderpass_ids[particle_idx] = current_renderpass;
        lifetimes[particle_idx] = 0.5;
        velocities[particle_idx] = vec4(0);
        positions[particle_idx].xyz = projectile_position.xyz + offset.xyz;
    }
}