#version 430
layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0) uniform sampler2D source_depth_texture;
layout(binding = 1) uniform sampler2D target_depth_texture;

layout(rgba32f, binding = 0) uniform image2D source_image;
layout(rgba32f, binding = 1) uniform image2D target_image;

layout(location = 0) uniform vec2 source_size;
layout(location = 1) uniform vec2 target_size;

void main() {
    ivec2 inv_id = ivec2(gl_GlobalInvocationID.xy);
    
    // -- center of pixel for accurate sampling
    vec2 source_texcoord = (vec2(inv_id) + 0.5) / source_size;
    vec2 target_texcoord = (vec2(inv_id) + 0.5) / target_size;
    
    float source_depth = texture(source_depth_texture, source_texcoord).r;
    float target_depth = texture(target_depth_texture, target_texcoord).r;
    
    vec4 source_color = imageLoad(source_image, inv_id);
    vec4 target_color = imageLoad(target_image, inv_id);
    
    vec4 out_color = target_color;  // -- default to target color
    
    // -- only blend if source has non-zero opacity
    if(source_depth <= target_depth && source_color.a > 0) {
        // -- source over target blending
        out_color.rgb = source_color.rgb * source_color.a + 
                        target_color.rgb * (1.0 - source_color.a);
        out_color.a = source_color.a + target_color.a * (1.0 - source_color.a);
    }
    
    imageStore(target_image, inv_id, out_color);
}